name: nyc_bus
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3
    - dill=0.2.5
    - Flask=0.12.4
    - gunicorn=19.3.0
    - Jinja2=2.8
    - requests>=2.9.0
    - numpy=1.10.4
    - pandas=0.18.1
    - Flask-WTF=0.14.2
    - WTForms=2.1
    - bokeh=0.12.5
    - ujson=1.35
    - werkzeug=0.12.2
